### ISSUE TITLE
Add website for the project.

### ISSUE THREAD

**Issue by samyakbhuta** [kartikm/fonts-aakar#10]
Add 'http://kartikm.github.io/fonts-aakar/' as website in repo's settings. Can't do it myself.

**Comment by kartikm** [comment]
Where exactly?

**Comment by samyakbhuta** [comment]
Click on **Edit** button/link, next to project description in the repo main page. You will see two textfields. One for **Description**, other for **Website**.
![screen shot 2013-12-01 at 10 41 47 pm](https://f.cloud.github.com/assets/738746/1650757/ee8730fa-5aab-11e3-886f-1bc111123518.png)

**Comment by kartikm** [comment]
Done. Thanks!
