### ISSUE TITLE
Should Aakar have it's own twitter handle @font_aakar ?

### ISSUE THREAD

**Issue by samyakbhuta** [kartikm/fonts-aakar#23]
- Helps people to follow whatever is taking place in and around Aakar
- Allows people to mention and shout-out
- Allows people to ask question and file bug
- Gives a personality, or - Ahem ! since it is already a typeface - adds to the personality
- You never know !

Just imagine @font_aakar tweeting 
- `@font_rekha happy birthday`
- `@font_rekha congratulation on improved 'ષ' glyph support. Though, serifs still sucks.`

**Comment by kartikm** [comment]
Too much. :-1:

**Comment by samyakbhuta** [comment]
Ok. Closing it.
