### ISSUE TITLE
Could not install the font using apt-get command on Ubuntu 12.04 LTS

### ISSUE THREAD

**Issue by lakhansamani** [kartikm/fonts-aakar#27]
I tried to follow the instructions to install font on my Ubuntu machine. Following is the command I used.

```
sudo apt-get install fonts-aakar
```

Following was the output after running the command

```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package fonts-aakar
```

Let me know if more details are needed from my side.

**Comment by kartikm** [comment]
You need to install, `fonts-gujr-extra` package which has Aakar and Rekha fonts.
