### ISSUE TITLE
Create dedicated website for the font

### ISSUE THREAD

**Issue by samyakbhuta** [kartikm/fonts-aakar#7]
- Helps to point out to people
- Helps people to discover
- [brew](http://brew.sh/) demands that packages/projects need to have a website.

**Comment by samyakbhuta** [comment]
@kartikm, Can you create an empty `gh-pages` branch so I can push content from my repo to that branch ? The website is currently live at http://samyakbhuta.github.io/fonts-aakar/.

See also http://stackoverflow.com/questions/9796370/github-pull-request-to-a-new-upstream-branch.

**Comment by kartikm** [comment]
@samyakbhuta added you as collaborator, so you'll be able to push it yourself :)

**Comment by samyakbhuta** [comment]
@kartikm thanks. On it.

**Comment by samyakbhuta** [comment]
It is now live at http://kartikm.github.io/fonts-aakar/.
